server.port=8080
spring.application.name=gateway-service

# Eureka Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ROUTES
# 1. Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# 2. Quantity Service
spring.cloud.gateway.routes[1].id=quantity-service
spring.cloud.gateway.routes[1].uri=lb://QUANTITY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/quantities/**


