# Railway variables use karega, agar nahi mile toh local connect karega
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quantity_measurement}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Whatiscar123@}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security debug ke liye (Problem aane par logs check karne ke liye)
logging.level.org.springframework.security=DEBUG
server.port=${PORT:8080}